config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get    'signup', to: 'users#new'
  # login、logoutというパスでそれぞれ、ログイン、ログアウトできるようにしている
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get  'edit_address', to: 'users#edit_address'
      patch 'edit_address_complete', to: 'users#edit_address_complete'
      get 'following_users'
      get 'follower_users'
    end


  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]


end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  # on: :update　以下のメソッドの時だけ実行される
  validates :age , numericality: { only_integer: true , greater_than_or_equal_to: 0}, length: { maximum: 3 }, on: :update
  validates :address , length: { maximum: 10}, on: :update

  has_many :microposts

  ########################################################################################################################
  # following_relationshipsのforeign_keyのfollower_idにuserのidが入るので、user.following_relationshipsによって、
  # userがフォローしている場合のrelationshipの集まりを取得
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  # throughには、following_relationshipsが指定されていて、following_relationshipsを経由してフォローしているユーザーの集まりを取得
  # userがフォローしている人は、following_relationshipsのfollowed_idに一致するユーザーになるので、sourceとしてfollowedを指定
  has_many :following_users, through: :following_relationships, source: :followed

  # -----------------------------------------------------------------------------------------------------------------------
  # follower_relationshipsのforeign_keyのfollowed_idにuserのidが入るので、
  # user.follower_relationshipsによって、userがフォローされている場合のrelationshipの集まりを取得
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  # throughには、follower_relationshipsが指定されていて、follower_relationshipsを経由してuserがフォローされているユーザーの集まりを取得
  # userをフォローしている人は、follower_relationshipsのfollower_idに一致するユーザーになるので、sourceとしてfollowerを指定
  has_many :follower_users, through: :follower_relationships, source: :follower

  # -----------------------------------------------------------------------------------------------------------------------

  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  ########################################################################################################################
  
  # タイムライン表示
  # user_idがフォローしているユーザーと自分のつぶやきを取得
  # following_user_idsは、Userモデルのhas_many :following_usersの部分で自動的に生成されたメソッドで、
  # フォローしているユーザーのIDを配列で返します。配列同士は、+で要素を足し合わせる。
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # edit,updateメソッドの前にset_messageを実行
  before_action :set_message, only: [:edit, :update, :destroy, :edit_address, :edit_address_complete]
  before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(created_at: :desc)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
      # 上記と同じ動きをする
      # redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit_address
    # 指定したrenderでviewを作成する
    render 'edit_address_test'
  end

  def edit_address_complete

    if @user.update(user_update_params)
      # nowを入れると一回だけ表示。そうじゃないと、メッセージが残る
      flash.now[:success] = "プロフィールを更新しましたよ。"
      # viewのファイル名を指定する
      render 'edit_address_test'
    else
      @users = User.all
      flash.now[:danger] = "更新内容にエラーがありますよ。"
      # viewのファイル名を指定する
      render 'edit_address_test'

    end
  end

  def edit
  end

  def update

    if @user.update(user_update_params)
      # nowを入れると一回だけ表示。そうじゃないと、メッセージが残る
      flash.now[:success] = "プロフィールを更新しました。"
      render 'edit'
    else
      @users = User.all
      flash.now[:danger] = "更新内容にエラーがあります。"
      render 'edit'
    end
  end

  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  def following_users
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following_users.page(params[:page])
    render 'show_follow'
  end

  def follower_users
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.follower_users.page(params[:page])
    render 'show_follow'
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def user_update_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :age, :address)
  end

  def set_message
    @user = User.find(params[:id])
  end

  # 正しいユーザーかどうかチェック
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<% if @users.any? %>
  <li id="followusers-<%= user.id %>">
    <%= link_to gravatar_for(user, size: 50), user %>
    <span class="user"><%= link_to user.name, user %></span>
  </li>
<% end %>

app/views/users/edit.html.erb
<h1>Settings</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <!-- #これで@userが新しいときはuser#createに#@userが既存のときは、user#updateに, 勝手に振り分ける -->

      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name ,class: 'form-control' %>

      <%= f.label :email, "メルアド" %>
      <%= f.text_field :email ,class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password ,class: 'form-control' %>

      <%= f.label :password_confirmation, "確認パスワード" %>
      <%= f.password_field :password_confirmation ,class: 'form-control' %>

      <%= f.label :age %>
      <%= f.text_field :age ,class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address ,class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit_address_test.erb
<h1>Settings</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: {action: 'edit_address_complete'}) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :address %>
      <%= f.text_field :address ,class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name ,class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email ,class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password ,class: 'form-control' %>

      <%= f.label :password_confirmation, "確認パスワード" %>
      <%= f.password_field :password_confirmation ,class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
        <!--
        上記の内容＿その１
        <%= render partial: 'microposts/micropost', collection: @microposts %>
        上記の内容＿その２
        <% @microposts.each do |micropost| %>
          <%= render partial: 'microposts/micropost', locals: { micropost: micropost } %>
        <% end %>
        -->
      </ol>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="user_info">
      <h1>
        <% @user ||= current_user %>
        <div>
          <a href="<%= following_users_user_path(@user) %>">
            <strong>
              <%= @user.following_users.count %>
            </strong>
            following
          </a>
        </div>
        <div>
          <a href="<%= follower_users_user_path(@user) %>">
            <strong>
              <%= @user.follower_users.count %>
            </strong>
            followers
          </a>
        </div>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="followusers">
        <% if @users.any? %>
          <% @users.each do |user| %>
            <li id="followusers-<%= user.id %>">
              <%= link_to gravatar_for(user, size: 50), user %>
              <span class="user"><%= link_to user.name, user %></span>
            </li>
          <% end %>
          <%= paginate @users %>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>